INSERT INTO keywords (word, category)
VALUES
-- Artificial Intelligence
('machine learning', 'Artificial Intelligence'),
('deep learning', 'Artificial Intelligence'),
('neural networks', 'Artificial Intelligence'),
('computer vision', 'Artificial Intelligence'),
('natural language processing', 'Artificial Intelligence'),
('AI ethics', 'Artificial Intelligence'),
('reinforcement learning', 'Artificial Intelligence'),
('chatbots', 'Artificial Intelligence'),
('speech recognition', 'Artificial Intelligence'),
('generative AI', 'Artificial Intelligence'),

-- Cybersecurity
('penetration testing', 'Cybersecurity'),
('firewall', 'Cybersecurity'),
('zero-day exploit', 'Cybersecurity'),
('DDoS attack', 'Cybersecurity'),
('phishing', 'Cybersecurity'),
('ransomware', 'Cybersecurity'),
('malware analysis', 'Cybersecurity'),
('social engineering', 'Cybersecurity'),
('encryption', 'Cybersecurity'),
('password security', 'Cybersecurity'),

-- Programming Languages
('Java', 'Programming Languages'),
('Python', 'Programming Languages'),
('JavaScript', 'Programming Languages'),
('C++', 'Programming Languages'),
('C#', 'Programming Languages'),
('Go', 'Programming Languages'),
('Rust', 'Programming Languages'),
('Kotlin', 'Programming Languages'),
('Swift', 'Programming Languages'),
('TypeScript', 'Programming Languages'),

-- Software Development
('object-oriented programming', 'Software Development'),
('agile methodology', 'Software Development'),
('scrum', 'Software Development'),
('test-driven development', 'Software Development'),
('design patterns', 'Software Development'),
('debugging', 'Software Development'),
('unit testing', 'Software Development'),
('version control', 'Software Development'),
('continuous integration', 'Software Development'),
('DevOps', 'Software Development'),

-- Open Source Technologies
('Linux', 'Open Source Technologies'),
('GitHub', 'Open Source Technologies'),
('Apache', 'Open Source Technologies'),
('MySQL', 'Open Source Technologies'),
('PostgreSQL', 'Open Source Technologies'),
('Docker', 'Open Source Technologies'),
('Kubernetes', 'Open Source Technologies'),
('Nginx', 'Open Source Technologies'),
('Redis', 'Open Source Technologies'),
('TensorFlow', 'Open Source Technologies'),

-- Hardware & Gadgets
('graphics card', 'Hardware & Gadgets'),
('SSD', 'Hardware & Gadgets'),
('gaming laptop', 'Hardware & Gadgets'),
('custom PC build', 'Hardware & Gadgets'),
('overclocking', 'Hardware & Gadgets'),
('Raspberry Pi', 'Hardware & Gadgets'),
('Arduino', 'Hardware & Gadgets'),
('mechanical keyboard', 'Hardware & Gadgets'),
('smartwatch', 'Hardware & Gadgets'),
('VR headset', 'Hardware & Gadgets'),

-- Networking & IT Infrastructure
('IP address', 'Networking & IT Infrastructure'),
('VPN', 'Networking & IT Infrastructure'),
('router configuration', 'Networking & IT Infrastructure'),
('subnetting', 'Networking & IT Infrastructure'),
('firewall rules', 'Networking & IT Infrastructure'),
('DNS', 'Networking & IT Infrastructure'),
('load balancing', 'Networking & IT Infrastructure'),
('wireless security', 'Networking & IT Infrastructure'),
('Ethernet', 'Networking & IT Infrastructure'),
('data center', 'Networking & IT Infrastructure'),

-- Cloud Computing
('AWS', 'Cloud Computing'),
('Azure', 'Cloud Computing'),
('Google Cloud Platform', 'Cloud Computing'),
('serverless computing', 'Cloud Computing'),
('cloud storage', 'Cloud Computing'),
('Kubernetes', 'Cloud Computing'),
('cloud security', 'Cloud Computing'),
('multi-cloud', 'Cloud Computing'),
('hybrid cloud', 'Cloud Computing'),
('CI/CD pipelines', 'Cloud Computing'),

-- Data Science & Analytics
('big data', 'Data Science & Analytics'),
('data visualization', 'Data Science & Analytics'),
('data mining', 'Data Science & Analytics'),
('SQL queries', 'Data Science & Analytics'),
('ETL process', 'Data Science & Analytics'),
('data warehousing', 'Data Science & Analytics'),
('predictive analytics', 'Data Science & Analytics'),
('data engineering', 'Data Science & Analytics'),
('business intelligence', 'Data Science & Analytics'),
('statistical modeling', 'Data Science & Analytics'),

-- Blockchain & Cryptocurrency
('Bitcoin', 'Blockchain & Cryptocurrency'),
('Ethereum', 'Blockchain & Cryptocurrency'),
('smart contracts', 'Blockchain & Cryptocurrency'),
('NFTs', 'Blockchain & Cryptocurrency'),
('crypto mining', 'Blockchain & Cryptocurrency'),
('DeFi', 'Blockchain & Cryptocurrency'),
('blockchain security', 'Blockchain & Cryptocurrency'),
('cryptographic hashing', 'Blockchain & Cryptocurrency'),
('wallet security', 'Blockchain & Cryptocurrency'),
('stablecoins', 'Blockchain & Cryptocurrency'),

-- Operating Systems
('Windows 11', 'Operating Systems'),
('macOS', 'Operating Systems'),
('Linux', 'Operating Systems'),
('Ubuntu', 'Operating Systems'),
('Android', 'Operating Systems'),
('iOS', 'Operating Systems'),
('file system', 'Operating Systems'),
('kernel', 'Operating Systems'),
('process management', 'Operating Systems'),
('shell scripting', 'Operating Systems'),

-- Web Development
('HTML5', 'Web Development'),
('CSS3', 'Web Development'),
('JavaScript frameworks', 'Web Development'),
('ReactJS', 'Web Development'),
('VueJS', 'Web Development'),
('Angular', 'Web Development'),
('REST APIs', 'Web Development'),
('GraphQL', 'Web Development'),
('frontend development', 'Web Development'),
('backend development', 'Web Development');

INSERT INTO keywords (word, category)
VALUES
-- Physics
('quantum mechanics', 'Physics'),
('theory of relativity', 'Physics'),
('thermodynamics', 'Physics'),
('electromagnetism', 'Physics'),
('particle physics', 'Physics'),
('string theory', 'Physics'),
('gravitational waves', 'Physics'),
('nuclear physics', 'Physics'),
('fluid dynamics', 'Physics'),
('optics', 'Physics'),

-- Chemistry
('organic chemistry', 'Chemistry'),
('inorganic chemistry', 'Chemistry'),
('chemical bonding', 'Chemistry'),
('stoichiometry', 'Chemistry'),
('molecular reactions', 'Chemistry'),
('analytical chemistry', 'Chemistry'),
('biochemistry', 'Chemistry'),
('polymer science', 'Chemistry'),
('spectroscopy', 'Chemistry'),
('thermochemistry', 'Chemistry'),

-- Biology
('genetics', 'Biology'),
('evolution', 'Biology'),
('microbiology', 'Biology'),
('biotechnology', 'Biology'),
('cell biology', 'Biology'),
('human anatomy', 'Biology'),
('physiology', 'Biology'),
('botany', 'Biology'),
('zoology', 'Biology'),
('ecology', 'Biology'),

-- Environmental Science
('climate change', 'Environmental Science'),
('renewable energy', 'Environmental Science'),
('sustainability', 'Environmental Science'),
('biodiversity', 'Environmental Science'),
('carbon footprint', 'Environmental Science'),
('ozone depletion', 'Environmental Science'),
('conservation biology', 'Environmental Science'),
('pollution control', 'Environmental Science'),
('green technology', 'Environmental Science'),
('environmental impact assessment', 'Environmental Science'),

-- Earth Science
('geology', 'Earth Science'),
('volcanology', 'Earth Science'),
('seismology', 'Earth Science'),
('hydrology', 'Earth Science'),
('plate tectonics', 'Earth Science'),
('fossil fuels', 'Earth Science'),
('oceanography', 'Earth Science'),
('meteorology', 'Earth Science'),
('atmospheric science', 'Earth Science'),
('soil science', 'Earth Science'),

-- Astronomy & Space Science
('astrophysics', 'Astronomy & Space Science'),
('cosmology', 'Astronomy & Space Science'),
('exoplanets', 'Astronomy & Space Science'),
('black holes', 'Astronomy & Space Science'),
('dark matter', 'Astronomy & Space Science'),
('space exploration', 'Astronomy & Space Science'),
('gravitational lensing', 'Astronomy & Space Science'),
('solar system', 'Astronomy & Space Science'),
('interstellar travel', 'Astronomy & Space Science'),
('SETI', 'Astronomy & Space Science'),

-- Mathematics
('calculus', 'Mathematics'),
('linear algebra', 'Mathematics'),
('probability theory', 'Mathematics'),
('statistics', 'Mathematics'),
('number theory', 'Mathematics'),
('combinatorics', 'Mathematics'),
('game theory', 'Mathematics'),
('differential equations', 'Mathematics'),
('mathematical modeling', 'Mathematics'),
('graph theory', 'Mathematics'),

-- Electrical Engineering
('circuit design', 'Electrical Engineering'),
('power electronics', 'Electrical Engineering'),
('microcontrollers', 'Electrical Engineering'),
('semiconductor physics', 'Electrical Engineering'),
('digital signal processing', 'Electrical Engineering'),
('electrical safety', 'Electrical Engineering'),
('wireless communication', 'Electrical Engineering'),
('radio frequency engineering', 'Electrical Engineering'),
('electromagnetic compatibility', 'Electrical Engineering'),
('control systems', 'Electrical Engineering'),

-- Mechanical Engineering
('thermodynamics', 'Mechanical Engineering'),
('fluid mechanics', 'Mechanical Engineering'),
('mechanical vibrations', 'Mechanical Engineering'),
('solid mechanics', 'Mechanical Engineering'),
('computer-aided design', 'Mechanical Engineering'),
('robotics', 'Mechanical Engineering'),
('HVAC systems', 'Mechanical Engineering'),
('aerospace engineering', 'Mechanical Engineering'),
('automobile engineering', 'Mechanical Engineering'),
('mechatronics', 'Mechanical Engineering'),

-- Civil Engineering
('structural analysis', 'Civil Engineering'),
('construction materials', 'Civil Engineering'),
('geotechnical engineering', 'Civil Engineering'),
('hydraulic structures', 'Civil Engineering'),
('transportation engineering', 'Civil Engineering'),
('urban planning', 'Civil Engineering'),
('earthquake engineering', 'Civil Engineering'),
('surveying', 'Civil Engineering'),
('bridge design', 'Civil Engineering'),
('environmental engineering', 'Civil Engineering'),

-- Chemical Engineering
('chemical process design', 'Chemical Engineering'),
('thermochemical processes', 'Chemical Engineering'),
('biochemical engineering', 'Chemical Engineering'),
('process control', 'Chemical Engineering'),
('polymer engineering', 'Chemical Engineering'),
('reaction kinetics', 'Chemical Engineering'),
('mass transfer', 'Chemical Engineering'),
('separation processes', 'Chemical Engineering'),
('petrochemical engineering', 'Chemical Engineering'),
('fluidization', 'Chemical Engineering'),

-- Biomedical Engineering
('biomechanics', 'Biomedical Engineering'),
('prosthetics', 'Biomedical Engineering'),
('medical imaging', 'Biomedical Engineering'),
('tissue engineering', 'Biomedical Engineering'),
('bioinformatics', 'Biomedical Engineering'),
('biomedical instrumentation', 'Biomedical Engineering'),
('nanomedicine', 'Biomedical Engineering'),
('biomaterials', 'Biomedical Engineering'),
('gene therapy', 'Biomedical Engineering'),
('artificial organs', 'Biomedical Engineering'),

-- Aerospace Engineering
('aerodynamics', 'Aerospace Engineering'),
('space propulsion', 'Aerospace Engineering'),
('orbital mechanics', 'Aerospace Engineering'),
('hypersonic flight', 'Aerospace Engineering'),
('aviation safety', 'Aerospace Engineering'),
('satellite technology', 'Aerospace Engineering'),
('unmanned aerial vehicles', 'Aerospace Engineering'),
('spacecraft design', 'Aerospace Engineering'),
('fluid dynamics', 'Aerospace Engineering'),
('air traffic control', 'Aerospace Engineering'),

-- Materials Science & Engineering
('metallurgy', 'Materials Science & Engineering'),
('nanotechnology', 'Materials Science & Engineering'),
('ceramics', 'Materials Science & Engineering'),
('composite materials', 'Materials Science & Engineering'),
('polymers', 'Materials Science & Engineering'),
('smart materials', 'Materials Science & Engineering'),
('crystallography', 'Materials Science & Engineering'),
('thin film coatings', 'Materials Science & Engineering'),
('biocompatible materials', 'Materials Science & Engineering'),
('corrosion science', 'Materials Science & Engineering');

INSERT INTO keywords (word, category)
VALUES
-- General Automotive Terms
('automobile', 'Automobiles'),
('car', 'Automobiles'),
('motorcycle', 'Motorcycles'),
('scooter', 'Motorcycles'),
('vehicle', 'Automobiles'),
('engine', 'Automobiles'),
('horsepower', 'Automobiles'),
('torque', 'Automobiles'),
('transmission', 'Automobiles'),
('drivetrain', 'Automobiles'),

-- Car Brands
('toyota', 'Automobiles'),
('honda', 'Automobiles'),
('ford', 'Automobiles'),
('chevrolet', 'Automobiles'),
('bmw', 'Automobiles'),
('mercedes-benz', 'Automobiles'),
('audi', 'Automobiles'),
('volkswagen', 'Automobiles'),
('porsche', 'Automobiles'),
('tesla', 'Automobiles'),

-- Motorcycle Brands
('harley-davidson', 'Motorcycles'),
('yamaha', 'Motorcycles'),
('suzuki', 'Motorcycles'),
('kawasaki', 'Motorcycles'),
('ducati', 'Motorcycles'),
('ktm', 'Motorcycles'),
('bmw motorrad', 'Motorcycles'),
('triumph', 'Motorcycles'),
('royal enfield', 'Motorcycles'),
('honda motorcycles', 'Motorcycles'),

-- Car Types
('sedan', 'Automobiles'),
('suv', 'Automobiles'),
('crossover', 'Automobiles'),
('coupe', 'Automobiles'),
('convertible', 'Automobiles'),
('hatchback', 'Automobiles'),
('pickup truck', 'Automobiles'),
('van', 'Automobiles'),
('electric vehicle', 'Automobiles'),
('hybrid car', 'Automobiles'),

-- Motorcycle Types
('sport bike', 'Motorcycles'),
('cruiser', 'Motorcycles'),
('touring motorcycle', 'Motorcycles'),
('dirt bike', 'Motorcycles'),
('dual-sport motorcycle', 'Motorcycles'),
('adventure bike', 'Motorcycles'),
('cafe racer', 'Motorcycles'),
('naked bike', 'Motorcycles'),
('chopper', 'Motorcycles'),
('scooter', 'Motorcycles'),

-- Automotive Parts
('brake system', 'Automobiles'),
('clutch', 'Automobiles'),
('radiator', 'Automobiles'),
('suspension', 'Automobiles'),
('exhaust system', 'Automobiles'),
('turbocharger', 'Automobiles'),
('catalytic converter', 'Automobiles'),
('air filter', 'Automobiles'),
('oil filter', 'Automobiles'),
('carburetor', 'Automobiles'),

-- Motorcycle Parts
('handlebars', 'Motorcycles'),
('footpegs', 'Motorcycles'),
('engine guard', 'Motorcycles'),
('exhaust pipe', 'Motorcycles'),
('windshield', 'Motorcycles'),
('fairing', 'Motorcycles'),
('chain drive', 'Motorcycles'),
('clutch lever', 'Motorcycles'),
('brake lever', 'Motorcycles'),
('fuel tank', 'Motorcycles'),

-- Car Performance & Tuning
('performance tuning', 'Automobiles'),
('dyno tuning', 'Automobiles'),
('aftermarket parts', 'Automobiles'),
('turbocharging', 'Automobiles'),
('supercharging', 'Automobiles'),
('fuel injection', 'Automobiles'),
('engine remapping', 'Automobiles'),
('nitrous oxide', 'Automobiles'),
('aerodynamics', 'Automobiles'),
('sports suspension', 'Automobiles'),

-- Motorcycle Performance & Customization
('engine tuning', 'Motorcycles'),
('aftermarket exhaust', 'Motorcycles'),
('fuel remapping', 'Motorcycles'),
('custom paint', 'Motorcycles'),
('track racing setup', 'Motorcycles'),
('drag racing motorcycle', 'Motorcycles'),
('wheelie control', 'Motorcycles'),
('stunt riding', 'Motorcycles'),
('motorcycle ergonomics', 'Motorcycles'),
('custom fairings', 'Motorcycles'),

-- Car Racing & Motorsports
('formula 1', 'Automobiles'),
('nascar', 'Automobiles'),
('drag racing', 'Automobiles'),
('rally racing', 'Automobiles'),
('drifting', 'Automobiles'),
('endurance racing', 'Automobiles'),
('off-road racing', 'Automobiles'),
('time attack', 'Automobiles'),
('hill climb racing', 'Automobiles'),
('touring car racing', 'Automobiles'),

-- Motorcycle Racing & Motorsports
('motoGP', 'Motorcycles'),
('superbike racing', 'Motorcycles'),
('motocross', 'Motorcycles'),
('enduro racing', 'Motorcycles'),
('flat track racing', 'Motorcycles'),
('hill climb motorcycle', 'Motorcycles'),
('drag bike racing', 'Motorcycles'),
('speedway motorcycle racing', 'Motorcycles'),
('ice racing', 'Motorcycles'),
('stunt competitions', 'Motorcycles'),

-- Car Maintenance & Repair
('oil change', 'Automobiles'),
('tire rotation', 'Automobiles'),
('brake replacement', 'Automobiles'),
('engine diagnostics', 'Automobiles'),
('wheel alignment', 'Automobiles'),
('spark plug replacement', 'Automobiles'),
('timing belt replacement', 'Automobiles'),
('battery maintenance', 'Automobiles'),
('air conditioning repair', 'Automobiles'),
('fuel system cleaning', 'Automobiles'),

-- Motorcycle Maintenance & Repair
('chain maintenance', 'Motorcycles'),
('brake pad replacement', 'Motorcycles'),
('tire pressure check', 'Motorcycles'),
('oil filter change', 'Motorcycles'),
('engine tuning', 'Motorcycles'),
('coolant flush', 'Motorcycles'),
('cable lubrication', 'Motorcycles'),
('clutch adjustment', 'Motorcycles'),
('suspension tuning', 'Motorcycles'),
('battery maintenance', 'Motorcycles'),

-- Car Safety & Regulations
('seat belt laws', 'Automobiles'),
('airbag system', 'Automobiles'),
('crash test ratings', 'Automobiles'),
('road safety', 'Automobiles'),
('defensive driving', 'Automobiles'),
('traffic laws', 'Automobiles'),
('drunk driving prevention', 'Automobiles'),
('lane departure warning', 'Automobiles'),
('adaptive cruise control', 'Automobiles'),
('autonomous vehicles', 'Automobiles'),

-- Motorcycle Safety & Regulations
('helmet laws', 'Motorcycles'),
('protective gear', 'Motorcycles'),
('defensive riding', 'Motorcycles'),
('motorcycle insurance', 'Motorcycles'),
('road hazards for bikers', 'Motorcycles'),
('lane splitting laws', 'Motorcycles'),
('motorcycle ABS', 'Motorcycles'),
('high-visibility gear', 'Motorcycles'),
('motorcycle safety courses', 'Motorcycles'),
('rider fatigue awareness', 'Motorcycles');

INSERT INTO keywords (word, category)
VALUES
-- General Business Terms
('business', 'Business'),
('company', 'Business'),
('corporation', 'Business'),
('startup', 'Business'),
('entrepreneur', 'Business'),
('business model', 'Business'),
('mergers and acquisitions', 'Business'),
('business growth', 'Business'),
('small business', 'Business'),
('business strategy', 'Business'),

-- Finance & Investments
('finance', 'Finance'),
('investment', 'Finance'),
('stock market', 'Finance'),
('mutual funds', 'Finance'),
('dividends', 'Finance'),
('bonds', 'Finance'),
('exchange-traded funds', 'Finance'),
('hedge funds', 'Finance'),
('private equity', 'Finance'),
('venture capital', 'Finance'),

-- Corporate Finance
('corporate finance', 'Finance'),
('financial planning', 'Finance'),
('capital budgeting', 'Finance'),
('risk management', 'Finance'),
('debt financing', 'Finance'),
('equity financing', 'Finance'),
('financial modeling', 'Finance'),
('cost of capital', 'Finance'),
('working capital management', 'Finance'),
('cash flow analysis', 'Finance'),

-- Banking & Financial Institutions
('banking', 'Finance'),
('commercial banking', 'Finance'),
('investment banking', 'Finance'),
('central banking', 'Finance'),
('monetary policy', 'Finance'),
('interest rates', 'Finance'),
('credit unions', 'Finance'),
('loans', 'Finance'),
('mortgages', 'Finance'),
('financial institutions', 'Finance'),

-- Accounting & Auditing
('accounting', 'Finance'),
('auditing', 'Finance'),
('financial statements', 'Finance'),
('balance sheet', 'Finance'),
('income statement', 'Finance'),
('cash flow statement', 'Finance'),
('cost accounting', 'Finance'),
('tax accounting', 'Finance'),
('internal auditing', 'Finance'),
('external auditing', 'Finance'),

-- Economic Concepts
('economics', 'Finance'),
('microeconomics', 'Finance'),
('macroeconomics', 'Finance'),
('supply and demand', 'Finance'),
('inflation', 'Finance'),
('deflation', 'Finance'),
('gross domestic product', 'Finance'),
('economic indicators', 'Finance'),
('monetary policy', 'Finance'),
('fiscal policy', 'Finance'),

-- Financial Markets & Trading
('trading', 'Finance'),
('forex', 'Finance'),
('cryptocurrency', 'Finance'),
('bitcoin', 'Finance'),
('ethereum', 'Finance'),
('blockchain', 'Finance'),
('commodity markets', 'Finance'),
('derivatives', 'Finance'),
('futures contracts', 'Finance'),
('options trading', 'Finance'),

-- Entrepreneurship & Startups
('startup funding', 'Business'),
('venture capital', 'Business'),
('business pitch', 'Business'),
('angel investors', 'Business'),
('scalability', 'Business'),
('bootstrapping', 'Business'),
('lean startup', 'Business'),
('minimum viable product', 'Business'),
('business incubators', 'Business'),
('accelerators', 'Business'),

-- Marketing & Sales
('marketing', 'Business'),
('digital marketing', 'Business'),
('content marketing', 'Business'),
('seo', 'Business'),
('social media marketing', 'Business'),
('email marketing', 'Business'),
('sales strategy', 'Business'),
('customer acquisition', 'Business'),
('brand management', 'Business'),
('public relations', 'Business'),

-- E-Commerce & Online Business
('e-commerce', 'Business'),
('dropshipping', 'Business'),
('affiliate marketing', 'Business'),
('online marketplace', 'Business'),
('subscription model', 'Business'),
('customer retention', 'Business'),
('conversion rate optimization', 'Business'),
('product listings', 'Business'),
('logistics', 'Business'),
('supply chain management', 'Business'),

-- Personal Finance
('personal finance', 'Finance'),
('budgeting', 'Finance'),
('saving money', 'Finance'),
('retirement planning', 'Finance'),
('401k', 'Finance'),
('roth ira', 'Finance'),
('credit score', 'Finance'),
('debt management', 'Finance'),
('financial independence', 'Finance'),
('passive income', 'Finance'),

-- Real Estate & Property Investment
('real estate', 'Finance'),
('property investment', 'Finance'),
('rental income', 'Finance'),
('mortgage rates', 'Finance'),
('house flipping', 'Finance'),
('commercial real estate', 'Finance'),
('residential real estate', 'Finance'),
('real estate crowdfunding', 'Finance'),
('property management', 'Finance'),
('home buying', 'Finance'),

-- Insurance & Risk Management
('insurance', 'Finance'),
('life insurance', 'Finance'),
('health insurance', 'Finance'),
('auto insurance', 'Finance'),
('home insurance', 'Finance'),
('disability insurance', 'Finance'),
('liability insurance', 'Finance'),
('business insurance', 'Finance'),
('actuarial science', 'Finance'),
('risk assessment', 'Finance'),

-- Corporate Law & Business Ethics
('corporate law', 'Business'),
('business ethics', 'Business'),
('contracts', 'Business'),
('intellectual property', 'Business'),
('trademark law', 'Business'),
('patents', 'Business'),
('corporate governance', 'Business'),
('labor law', 'Business'),
('antitrust law', 'Business'),
('compliance', 'Business'),

-- Leadership & Management
('leadership', 'Business'),
('management', 'Business'),
('organizational behavior', 'Business'),
('team building', 'Business'),
('decision making', 'Business'),
('strategic planning', 'Business'),
('conflict resolution', 'Business'),
('change management', 'Business'),
('workplace culture', 'Business'),
('employee engagement', 'Business'),

-- Business Productivity & Tools
('productivity', 'Business'),
('project management', 'Business'),
('time management', 'Business'),
('business automation', 'Business'),
('erp systems', 'Business'),
('crm software', 'Business'),
('kpis', 'Business'),
('performance metrics', 'Business'),
('business intelligence', 'Business'),
('market research', 'Business'),

-- Global Trade & Economics
('international trade', 'Finance'),
('import export', 'Finance'),
('tariffs', 'Finance'),
('trade agreements', 'Finance'),
('foreign exchange', 'Finance'),
('global supply chain', 'Finance'),
('world bank', 'Finance'),
('imf', 'Finance'),
('economic development', 'Finance'),
('outsourcing', 'Business');

INSERT INTO keywords (word, category)
VALUES
-- General Health
('health', 'Health & Fitness'),
('wellness', 'Health & Fitness'),
('nutrition', 'Health & Fitness'),
('healthy living', 'Health & Fitness'),
('preventive care', 'Health & Fitness'),
('public health', 'Health & Fitness'),
('holistic health', 'Health & Fitness'),
('functional medicine', 'Health & Fitness'),
('lifestyle medicine', 'Health & Fitness'),
('health education', 'Health & Fitness'),

-- Fitness & Exercise
('fitness', 'Health & Fitness'),
('workout', 'Health & Fitness'),
('exercise', 'Health & Fitness'),
('strength training', 'Health & Fitness'),
('weightlifting', 'Health & Fitness'),
('bodybuilding', 'Health & Fitness'),
('crossfit', 'Health & Fitness'),
('functional training', 'Health & Fitness'),
('cardio', 'Health & Fitness'),
('high-intensity interval training', 'Health & Fitness'),
('pilates', 'Health & Fitness'),
('yoga', 'Health & Fitness'),
('stretching', 'Health & Fitness'),
('aerobics', 'Health & Fitness'),
('home workouts', 'Health & Fitness'),
('gym workouts', 'Health & Fitness'),

-- Diet & Nutrition
('diet', 'Health & Fitness'),
('balanced diet', 'Health & Fitness'),
('calorie counting', 'Health & Fitness'),
('low-carb diet', 'Health & Fitness'),
('high-protein diet', 'Health & Fitness'),
('ketogenic diet', 'Health & Fitness'),
('paleo diet', 'Health & Fitness'),
('vegan diet', 'Health & Fitness'),
('vegetarian diet', 'Health & Fitness'),
('mediterranean diet', 'Health & Fitness'),
('intermittent fasting', 'Health & Fitness'),
('nutrition supplements', 'Health & Fitness'),
('protein shakes', 'Health & Fitness'),
('vitamins', 'Health & Fitness'),
('omega-3', 'Health & Fitness'),

-- Mental Health & Wellbeing
('mental health', 'Health & Fitness'),
('anxiety', 'Health & Fitness'),
('depression', 'Health & Fitness'),
('stress management', 'Health & Fitness'),
('meditation', 'Health & Fitness'),
('mindfulness', 'Health & Fitness'),
('self-care', 'Health & Fitness'),
('therapy', 'Health & Fitness'),
('counseling', 'Health & Fitness'),
('mental resilience', 'Health & Fitness'),
('work-life balance', 'Health & Fitness'),
('emotional wellbeing', 'Health & Fitness'),
('cbt therapy', 'Health & Fitness'),

-- Weight Management
('weight loss', 'Health & Fitness'),
('weight gain', 'Health & Fitness'),
('fat loss', 'Health & Fitness'),
('muscle gain', 'Health & Fitness'),
('metabolism', 'Health & Fitness'),
('caloric deficit', 'Health & Fitness'),
('bmi', 'Health & Fitness'),
('body composition', 'Health & Fitness'),
('obesity', 'Health & Fitness'),
('appetite control', 'Health & Fitness'),
('eating disorders', 'Health & Fitness'),

-- Sports & Athletics
('sports', 'Health & Fitness'),
('athletics', 'Health & Fitness'),
('running', 'Health & Fitness'),
('cycling', 'Health & Fitness'),
('swimming', 'Health & Fitness'),
('marathon training', 'Health & Fitness'),
('triathlon', 'Health & Fitness'),
('soccer fitness', 'Health & Fitness'),
('basketball training', 'Health & Fitness'),
('tennis fitness', 'Health & Fitness'),
('strength and conditioning', 'Health & Fitness'),

-- Sleep & Recovery
('sleep health', 'Health & Fitness'),
('sleep hygiene', 'Health & Fitness'),
('insomnia', 'Health & Fitness'),
('circadian rhythm', 'Health & Fitness'),
('power naps', 'Health & Fitness'),
('recovery', 'Health & Fitness'),
('muscle recovery', 'Health & Fitness'),
('post-workout recovery', 'Health & Fitness'),
('foam rolling', 'Health & Fitness'),
('sports massage', 'Health & Fitness'),

-- Medical Conditions & Diseases
('diabetes', 'Health & Fitness'),
('hypertension', 'Health & Fitness'),
('high blood pressure', 'Health & Fitness'),
('heart disease', 'Health & Fitness'),
('cholesterol', 'Health & Fitness'),
('arthritis', 'Health & Fitness'),
('osteoporosis', 'Health & Fitness'),
('cancer awareness', 'Health & Fitness'),
('asthma', 'Health & Fitness'),
('allergies', 'Health & Fitness'),

-- Alternative Medicine & Therapies
('alternative medicine', 'Health & Fitness'),
('chiropractic', 'Health & Fitness'),
('acupuncture', 'Health & Fitness'),
('homeopathy', 'Health & Fitness'),
('naturopathy', 'Health & Fitness'),
('herbal medicine', 'Health & Fitness'),
('essential oils', 'Health & Fitness'),
('ayurveda', 'Health & Fitness'),
('traditional chinese medicine', 'Health & Fitness'),

-- Sexual & Reproductive Health
('sexual health', 'Health & Fitness'),
('reproductive health', 'Health & Fitness'),
('fertility', 'Health & Fitness'),
('pregnancy', 'Health & Fitness'),
('contraception', 'Health & Fitness'),
('menopause', 'Health & Fitness'),
('hormonal balance', 'Health & Fitness'),
('testosterone', 'Health & Fitness'),
('estrogen', 'Health & Fitness'),

-- Senior Health & Longevity
('senior fitness', 'Health & Fitness'),
('healthy aging', 'Health & Fitness'),
('longevity', 'Health & Fitness'),
('anti-aging', 'Health & Fitness'),
('mobility exercises', 'Health & Fitness'),
('bone health', 'Health & Fitness'),
('arthritis management', 'Health & Fitness'),

-- Biohacking & Human Optimization
('biohacking', 'Health & Fitness'),
('nootropics', 'Health & Fitness'),
('cold therapy', 'Health & Fitness'),
('sauna therapy', 'Health & Fitness'),
('fasting', 'Health & Fitness'),
('wearable health tech', 'Health & Fitness'),
('red light therapy', 'Health & Fitness'),
('genetic testing', 'Health & Fitness'),
('cryotherapy', 'Health & Fitness'),

-- Workplace Health & Ergonomics
('workplace wellness', 'Health & Fitness'),
('ergonomics', 'Health & Fitness'),
('standing desks', 'Health & Fitness'),
('blue light blocking', 'Health & Fitness'),
('office fitness', 'Health & Fitness'),
('stress relief at work', 'Health & Fitness'),
('posture correction', 'Health & Fitness'),
('eye strain relief', 'Health & Fitness');

INSERT INTO keywords (word, category)
VALUES
-- General Entertainment
('entertainment', 'Entertainment & Media'),
('pop culture', 'Entertainment & Media'),
('celebrity news', 'Entertainment & Media'),
('viral trends', 'Entertainment & Media'),
('memes', 'Entertainment & Media'),
('gossip', 'Entertainment & Media'),
('streaming', 'Entertainment & Media'),
('live performances', 'Entertainment & Media'),
('awards shows', 'Entertainment & Media'),

-- Movies & TV Shows
('movies', 'Entertainment & Media'),
('cinema', 'Entertainment & Media'),
('hollywood', 'Entertainment & Media'),
('bollywood', 'Entertainment & Media'),
('film industry', 'Entertainment & Media'),
('blockbusters', 'Entertainment & Media'),
('independent films', 'Entertainment & Media'),
('movie reviews', 'Entertainment & Media'),
('tv shows', 'Entertainment & Media'),
('binge-watching', 'Entertainment & Media'),
('netflix', 'Entertainment & Media'),
('disney+', 'Entertainment & Media'),
('hbo max', 'Entertainment & Media'),
('amazon prime video', 'Entertainment & Media'),
('hulu', 'Entertainment & Media'),
('crime dramas', 'Entertainment & Media'),
('sitcoms', 'Entertainment & Media'),
('reality tv', 'Entertainment & Media'),
('animated series', 'Entertainment & Media'),
('anime', 'Entertainment & Media'),

-- Music
('music', 'Entertainment & Media'),
('pop music', 'Entertainment & Media'),
('rock music', 'Entertainment & Media'),
('hip hop', 'Entertainment & Media'),
('rap', 'Entertainment & Media'),
('electronic music', 'Entertainment & Media'),
('edm', 'Entertainment & Media'),
('jazz', 'Entertainment & Media'),
('blues', 'Entertainment & Media'),
('country music', 'Entertainment & Media'),
('classical music', 'Entertainment & Media'),
('kpop', 'Entertainment & Media'),
('concerts', 'Entertainment & Media'),
('music festivals', 'Entertainment & Media'),
('album releases', 'Entertainment & Media'),
('music reviews', 'Entertainment & Media'),
('top charts', 'Entertainment & Media'),
('music industry', 'Entertainment & Media'),

-- Video Games
('gaming', 'Entertainment & Media'),
('video games', 'Entertainment & Media'),
('esports', 'Entertainment & Media'),
('game streaming', 'Entertainment & Media'),
('twitch', 'Entertainment & Media'),
('youtube gaming', 'Entertainment & Media'),
('playstation', 'Entertainment & Media'),
('xbox', 'Entertainment & Media'),
('nintendo', 'Entertainment & Media'),
('pc gaming', 'Entertainment & Media'),
('mobile gaming', 'Entertainment & Media'),
('indie games', 'Entertainment & Media'),
('rpg games', 'Entertainment & Media'),
('fps games', 'Entertainment & Media'),
('open-world games', 'Entertainment & Media'),
('strategy games', 'Entertainment & Media'),
('multiplayer games', 'Entertainment & Media'),
('game development', 'Entertainment & Media'),
('game reviews', 'Entertainment & Media'),
('gaming news', 'Entertainment & Media'),

-- Books & Literature
('books', 'Entertainment & Media'),
('literature', 'Entertainment & Media'),
('fiction', 'Entertainment & Media'),
('non-fiction', 'Entertainment & Media'),
('mystery novels', 'Entertainment & Media'),
('fantasy books', 'Entertainment & Media'),
('sci-fi books', 'Entertainment & Media'),
('romance novels', 'Entertainment & Media'),
('bestsellers', 'Entertainment & Media'),
('book reviews', 'Entertainment & Media'),
('audiobooks', 'Entertainment & Media'),
('poetry', 'Entertainment & Media'),
('comic books', 'Entertainment & Media'),
('graphic novels', 'Entertainment & Media'),

-- Social Media & Online Entertainment
('social media', 'Entertainment & Media'),
('youtube', 'Entertainment & Media'),
('tiktok', 'Entertainment & Media'),
('instagram reels', 'Entertainment & Media'),
('facebook videos', 'Entertainment & Media'),
('vlogging', 'Entertainment & Media'),
('influencers', 'Entertainment & Media'),
('content creators', 'Entertainment & Media'),
('viral videos', 'Entertainment & Media'),
('internet challenges', 'Entertainment & Media'),
('prank videos', 'Entertainment & Media'),

-- Podcasts & Radio
('podcasts', 'Entertainment & Media'),
('talk radio', 'Entertainment & Media'),
('comedy podcasts', 'Entertainment & Media'),
('true crime podcasts', 'Entertainment & Media'),
('history podcasts', 'Entertainment & Media'),
('sports podcasts', 'Entertainment & Media'),
('self-improvement podcasts', 'Entertainment & Media'),
('news podcasts', 'Entertainment & Media'),
('audiobooks', 'Entertainment & Media'),

-- Arts & Performing Arts
('theater', 'Entertainment & Media'),
('broadway', 'Entertainment & Media'),
('musicals', 'Entertainment & Media'),
('ballet', 'Entertainment & Media'),
('opera', 'Entertainment & Media'),
('stand-up comedy', 'Entertainment & Media'),
('improv', 'Entertainment & Media'),
('magic shows', 'Entertainment & Media'),

-- Fashion & Lifestyle
('fashion', 'Entertainment & Media'),
('celebrity style', 'Entertainment & Media'),
('runway shows', 'Entertainment & Media'),
('fashion trends', 'Entertainment & Media'),
('streetwear', 'Entertainment & Media'),
('luxury brands', 'Entertainment & Media'),
('fashion magazines', 'Entertainment & Media'),
('beauty trends', 'Entertainment & Media'),
('cosmetics', 'Entertainment & Media'),

-- Comics, Manga & Cartoons
('comics', 'Entertainment & Media'),
('dc comics', 'Entertainment & Media'),
('marvel comics', 'Entertainment & Media'),
('superheroes', 'Entertainment & Media'),
('manga', 'Entertainment & Media'),
('anime adaptations', 'Entertainment & Media'),
('cartoon network', 'Entertainment & Media'),
('saturday morning cartoons', 'Entertainment & Media'),

-- Theme Parks & Amusement
('theme parks', 'Entertainment & Media'),
('disneyland', 'Entertainment & Media'),
('universal studios', 'Entertainment & Media'),
('roller coasters', 'Entertainment & Media'),
('amusement parks', 'Entertainment & Media'),
('water parks', 'Entertainment & Media'),

-- Collectibles & Hobbies
('collectibles', 'Entertainment & Media'),
('action figures', 'Entertainment & Media'),
('trading cards', 'Entertainment & Media'),
('funko pop', 'Entertainment & Media'),
('hobby shops', 'Entertainment & Media'),
('board games', 'Entertainment & Media'),
('tabletop rpg', 'Entertainment & Media'),
('dungeons and dragons', 'Entertainment & Media'),
('lego', 'Entertainment & Media'),
('model building', 'Entertainment & Media'),

-- Celebrity Culture
('celebrities', 'Entertainment & Media'),
('movie stars', 'Entertainment & Media'),
('musicians', 'Entertainment & Media'),
('influencers', 'Entertainment & Media'),
('social media stars', 'Entertainment & Media'),
('tabloid news', 'Entertainment & Media'),
('celebrity scandals', 'Entertainment & Media'),
('paparazzi', 'Entertainment & Media');

INSERT INTO keywords (word, category)
VALUES
-- General Travel
('travel', 'Travel & Lifestyle'),
('vacation', 'Travel & Lifestyle'),
('tourism', 'Travel & Lifestyle'),
('travel destinations', 'Travel & Lifestyle'),
('travel tips', 'Travel & Lifestyle'),
('solo travel', 'Travel & Lifestyle'),
('backpacking', 'Travel & Lifestyle'),
('luxury travel', 'Travel & Lifestyle'),
('budget travel', 'Travel & Lifestyle'),
('travel photography', 'Travel & Lifestyle'),
('travel blogs', 'Travel & Lifestyle'),
('travel planning', 'Travel & Lifestyle'),
('cultural travel', 'Travel & Lifestyle'),
('historical sites', 'Travel & Lifestyle'),
('eco-tourism', 'Travel & Lifestyle'),
('adventure travel', 'Travel & Lifestyle'),
('digital nomad', 'Travel & Lifestyle'),

-- Transportation & Flights
('flights', 'Travel & Lifestyle'),
('airfare deals', 'Travel & Lifestyle'),
('airports', 'Travel & Lifestyle'),
('airlines', 'Travel & Lifestyle'),
('flight booking', 'Travel & Lifestyle'),
('business travel', 'Travel & Lifestyle'),
('frequent flyer miles', 'Travel & Lifestyle'),
('road trips', 'Travel & Lifestyle'),
('car rentals', 'Travel & Lifestyle'),
('train travel', 'Travel & Lifestyle'),
('cruise vacations', 'Travel & Lifestyle'),
('public transportation', 'Travel & Lifestyle'),

-- Accommodations & Lodging
('hotels', 'Travel & Lifestyle'),
('resorts', 'Travel & Lifestyle'),
('hostels', 'Travel & Lifestyle'),
('airbnb', 'Travel & Lifestyle'),
('vacation rentals', 'Travel & Lifestyle'),
('boutique hotels', 'Travel & Lifestyle'),
('eco-friendly hotels', 'Travel & Lifestyle'),
('glamping', 'Travel & Lifestyle'),

-- Popular Travel Destinations
('europe travel', 'Travel & Lifestyle'),
('asia travel', 'Travel & Lifestyle'),
('africa travel', 'Travel & Lifestyle'),
('north america travel', 'Travel & Lifestyle'),
('south america travel', 'Travel & Lifestyle'),
('australia travel', 'Travel & Lifestyle'),
('beach destinations', 'Travel & Lifestyle'),
('mountain retreats', 'Travel & Lifestyle'),
('national parks', 'Travel & Lifestyle'),
('island getaways', 'Travel & Lifestyle'),
('hidden gems', 'Travel & Lifestyle'),

-- Travel Activities & Experiences
('hiking', 'Travel & Lifestyle'),
('camping', 'Travel & Lifestyle'),
('scuba diving', 'Travel & Lifestyle'),
('snorkeling', 'Travel & Lifestyle'),
('safari tours', 'Travel & Lifestyle'),
('skiing', 'Travel & Lifestyle'),
('snowboarding', 'Travel & Lifestyle'),
('wildlife tours', 'Travel & Lifestyle'),
('city tours', 'Travel & Lifestyle'),
('museums', 'Travel & Lifestyle'),
('food tours', 'Travel & Lifestyle'),
('theme parks', 'Travel & Lifestyle'),

-- Travel Safety & Essentials
('travel insurance', 'Travel & Lifestyle'),
('travel scams', 'Travel & Lifestyle'),
('visa requirements', 'Travel & Lifestyle'),
('packing tips', 'Travel & Lifestyle'),
('essential travel gear', 'Travel & Lifestyle'),
('language barriers', 'Travel & Lifestyle'),
('currency exchange', 'Travel & Lifestyle'),

-- Lifestyle & Wellness
('lifestyle', 'Travel & Lifestyle'),
('healthy living', 'Travel & Lifestyle'),
('self-care', 'Travel & Lifestyle'),
('mental wellness', 'Travel & Lifestyle'),
('mindfulness', 'Travel & Lifestyle'),
('minimalism', 'Travel & Lifestyle'),
('home organization', 'Travel & Lifestyle'),
('personal growth', 'Travel & Lifestyle'),
('work-life balance', 'Travel & Lifestyle'),
('motivation', 'Travel & Lifestyle'),

-- Fashion & Style
('fashion', 'Travel & Lifestyle'),
('street style', 'Travel & Lifestyle'),
('seasonal fashion', 'Travel & Lifestyle'),
('wardrobe essentials', 'Travel & Lifestyle'),
('beauty routines', 'Travel & Lifestyle'),
('skincare', 'Travel & Lifestyle'),
('makeup trends', 'Travel & Lifestyle'),
('haircare', 'Travel & Lifestyle'),

-- Food & Drink
('food', 'Travel & Lifestyle'),
('cuisine', 'Travel & Lifestyle'),
('fine dining', 'Travel & Lifestyle'),
('street food', 'Travel & Lifestyle'),
('coffee culture', 'Travel & Lifestyle'),
('wine tasting', 'Travel & Lifestyle'),
('cocktail bars', 'Travel & Lifestyle'),
('food festivals', 'Travel & Lifestyle'),
('cooking classes', 'Travel & Lifestyle'),

-- Home & Interior Design
('home decor', 'Travel & Lifestyle'),
('interior design', 'Travel & Lifestyle'),
('furniture trends', 'Travel & Lifestyle'),
('home renovation', 'Travel & Lifestyle'),
('tiny homes', 'Travel & Lifestyle'),
('smart home technology', 'Travel & Lifestyle'),

-- Hobbies & Leisure
('hobbies', 'Travel & Lifestyle'),
('photography', 'Travel & Lifestyle'),
('gardening', 'Travel & Lifestyle'),
('calligraphy', 'Travel & Lifestyle'),
('knitting', 'Travel & Lifestyle'),
('DIY projects', 'Travel & Lifestyle'),
('journaling', 'Travel & Lifestyle'),
('meditation', 'Travel & Lifestyle'),
('yoga', 'Travel & Lifestyle'),
('surfing', 'Travel & Lifestyle'),
('cycling', 'Travel & Lifestyle'),

-- Events & Festivals
('music festivals', 'Travel & Lifestyle'),
('film festivals', 'Travel & Lifestyle'),
('fashion weeks', 'Travel & Lifestyle'),
('holiday markets', 'Travel & Lifestyle'),
('carnivals', 'Travel & Lifestyle'),
('sports events', 'Travel & Lifestyle'),
('cultural celebrations', 'Travel & Lifestyle'),

-- Social & Relationships
('friendship', 'Travel & Lifestyle'),
('dating', 'Travel & Lifestyle'),
('relationships', 'Travel & Lifestyle'),
('family life', 'Travel & Lifestyle'),
('parenting', 'Travel & Lifestyle'),
('marriage', 'Travel & Lifestyle'),
('social events', 'Travel & Lifestyle');

INSERT INTO keywords (word, category)
VALUES
-- General Sports
('sports', 'Sports & Recreation'),
('athletics', 'Sports & Recreation'),
('professional sports', 'Sports & Recreation'),
('sports news', 'Sports & Recreation'),
('sports training', 'Sports & Recreation'),
('sports injuries', 'Sports & Recreation'),
('sports betting', 'Sports & Recreation'),
('sports psychology', 'Sports & Recreation'),
('sports nutrition', 'Sports & Recreation'),
('sports gear', 'Sports & Recreation'),

-- Team Sports
('football', 'Sports & Recreation'),
('soccer', 'Sports & Recreation'),
('basketball', 'Sports & Recreation'),
('baseball', 'Sports & Recreation'),
('hockey', 'Sports & Recreation'),
('volleyball', 'Sports & Recreation'),
('rugby', 'Sports & Recreation'),
('cricket', 'Sports & Recreation'),
('handball', 'Sports & Recreation'),
('water polo', 'Sports & Recreation'),

-- Individual Sports
('tennis', 'Sports & Recreation'),
('table tennis', 'Sports & Recreation'),
('badminton', 'Sports & Recreation'),
('golf', 'Sports & Recreation'),
('boxing', 'Sports & Recreation'),
('mma', 'Sports & Recreation'),
('wrestling', 'Sports & Recreation'),
('fencing', 'Sports & Recreation'),
('archery', 'Sports & Recreation'),
('gymnastics', 'Sports & Recreation'),
('martial arts', 'Sports & Recreation'),
('judo', 'Sports & Recreation'),
('karate', 'Sports & Recreation'),
('taekwondo', 'Sports & Recreation'),
('muay thai', 'Sports & Recreation'),
('kickboxing', 'Sports & Recreation'),

-- Racing & Motorsports
('formula 1', 'Sports & Recreation'),
('nascar', 'Sports & Recreation'),
('motogp', 'Sports & Recreation'),
('rally racing', 'Sports & Recreation'),
('drag racing', 'Sports & Recreation'),
('touring car racing', 'Sports & Recreation'),
('karting', 'Sports & Recreation'),

-- Extreme & Adventure Sports
('skateboarding', 'Sports & Recreation'),
('bmx', 'Sports & Recreation'),
('parkour', 'Sports & Recreation'),
('snowboarding', 'Sports & Recreation'),
('skiing', 'Sports & Recreation'),
('mountain biking', 'Sports & Recreation'),
('rock climbing', 'Sports & Recreation'),
('bungee jumping', 'Sports & Recreation'),
('paragliding', 'Sports & Recreation'),
('wingsuit flying', 'Sports & Recreation'),
('base jumping', 'Sports & Recreation'),
('surfing', 'Sports & Recreation'),
('kitesurfing', 'Sports & Recreation'),
('windsurfing', 'Sports & Recreation'),
('whitewater rafting', 'Sports & Recreation'),

-- Water Sports
('swimming', 'Sports & Recreation'),
('diving', 'Sports & Recreation'),
('scuba diving', 'Sports & Recreation'),
('snorkeling', 'Sports & Recreation'),
('rowing', 'Sports & Recreation'),
('kayaking', 'Sports & Recreation'),
('sailing', 'Sports & Recreation'),
('water skiing', 'Sports & Recreation'),
('wakeboarding', 'Sports & Recreation'),

-- Track & Field
('running', 'Sports & Recreation'),
('sprinting', 'Sports & Recreation'),
('long-distance running', 'Sports & Recreation'),
('hurdles', 'Sports & Recreation'),
('marathon', 'Sports & Recreation'),
('decathlon', 'Sports & Recreation'),
('high jump', 'Sports & Recreation'),
('long jump', 'Sports & Recreation'),
('triple jump', 'Sports & Recreation'),
('pole vault', 'Sports & Recreation'),
('shot put', 'Sports & Recreation'),
('discus throw', 'Sports & Recreation'),
('javelin throw', 'Sports & Recreation'),

-- Strength & Fitness Sports
('bodybuilding', 'Sports & Recreation'),
('powerlifting', 'Sports & Recreation'),
('weightlifting', 'Sports & Recreation'),
('strongman', 'Sports & Recreation'),
('crossfit', 'Sports & Recreation'),
('calisthenics', 'Sports & Recreation'),
('parkour', 'Sports & Recreation'),

-- Hunting & Shooting Sports
('hunting', 'Sports & Recreation'),
('shooting sports', 'Sports & Recreation'),
('skeet shooting', 'Sports & Recreation'),
('trap shooting', 'Sports & Recreation'),
('airsoft', 'Sports & Recreation'),
('paintball', 'Sports & Recreation'),

-- Recreational Activities
('cycling', 'Sports & Recreation'),
('hiking', 'Sports & Recreation'),
('camping', 'Sports & Recreation'),
('fishing', 'Sports & Recreation'),
('bird watching', 'Sports & Recreation'),
('orienteering', 'Sports & Recreation'),
('horseback riding', 'Sports & Recreation'),

-- Winter Sports
('ice skating', 'Sports & Recreation'),
('figure skating', 'Sports & Recreation'),
('curling', 'Sports & Recreation'),
('sledding', 'Sports & Recreation'),
('ice hockey', 'Sports & Recreation'),
('biathlon', 'Sports & Recreation'),
('snowmobiling', 'Sports & Recreation'),

-- Esports & Competitive Gaming
('esports', 'Sports & Recreation'),
('competitive gaming', 'Sports & Recreation'),
('league of legends', 'Sports & Recreation'),
('dota 2', 'Sports & Recreation'),
('counter-strike', 'Sports & Recreation'),
('valorant', 'Sports & Recreation'),
('fortnite', 'Sports & Recreation'),
('call of duty', 'Sports & Recreation'),
('overwatch', 'Sports & Recreation'),
('fifa esports', 'Sports & Recreation'),
('rocket league', 'Sports & Recreation'),
('street fighter', 'Sports & Recreation'),
('tekken', 'Sports & Recreation'),
('super smash bros', 'Sports & Recreation'),
('fighting games', 'Sports & Recreation'),
('battle royale', 'Sports & Recreation'),
('moba games', 'Sports & Recreation'),
('racing simulators', 'Sports & Recreation'),

-- Major Sporting Events
('olympics', 'Sports & Recreation'),
('fifa world cup', 'Sports & Recreation'),
('uefa champions league', 'Sports & Recreation'),
('super bowl', 'Sports & Recreation'),
('nba finals', 'Sports & Recreation'),
('wimbledon', 'Sports & Recreation'),
('tour de france', 'Sports & Recreation'),
('cricket world cup', 'Sports & Recreation'),
('formula 1 grand prix', 'Sports & Recreation'),
('commonwealth games', 'Sports & Recreation');

INSERT INTO keywords (word, category)
VALUES
-- General Food & Cooking
('food', 'Food & Cooking'),
('cooking', 'Food & Cooking'),
('recipes', 'Food & Cooking'),
('culinary arts', 'Food & Cooking'),
('gastronomy', 'Food & Cooking'),
('chef', 'Food & Cooking'),
('home cooking', 'Food & Cooking'),
('gourmet', 'Food & Cooking'),
('cuisine', 'Food & Cooking'),
('meal prep', 'Food & Cooking'),
('food plating', 'Food & Cooking'),
('food science', 'Food & Cooking'),
('food trends', 'Food & Cooking'),

-- Cooking Techniques
('grilling', 'Food & Cooking'),
('roasting', 'Food & Cooking'),
('baking', 'Food & Cooking'),
('steaming', 'Food & Cooking'),
('boiling', 'Food & Cooking'),
(N'sautéing', 'Food & Cooking'),
('frying', 'Food & Cooking'),
('deep frying', 'Food & Cooking'),
('poaching', 'Food & Cooking'),
('sous vide', 'Food & Cooking'),
('slow cooking', 'Food & Cooking'),
('pressure cooking', 'Food & Cooking'),
('smoking', 'Food & Cooking'),
('stir-frying', 'Food & Cooking'),
('blanching', 'Food & Cooking'),
('braising', 'Food & Cooking'),

-- International Cuisines
('italian cuisine', 'Food & Cooking'),
('french cuisine', 'Food & Cooking'),
('chinese cuisine', 'Food & Cooking'),
('japanese cuisine', 'Food & Cooking'),
('korean cuisine', 'Food & Cooking'),
('mexican cuisine', 'Food & Cooking'),
('indian cuisine', 'Food & Cooking'),
('thai cuisine', 'Food & Cooking'),
('mediterranean cuisine', 'Food & Cooking'),
('greek cuisine', 'Food & Cooking'),
('spanish cuisine', 'Food & Cooking'),
('vietnamese cuisine', 'Food & Cooking'),
('brazilian cuisine', 'Food & Cooking'),
('lebanese cuisine', 'Food & Cooking'),
('turkish cuisine', 'Food & Cooking'),
('african cuisine', 'Food & Cooking'),
('caribbean cuisine', 'Food & Cooking'),

-- Ingredients & Spices
('herbs', 'Food & Cooking'),
('spices', 'Food & Cooking'),
('garlic', 'Food & Cooking'),
('onions', 'Food & Cooking'),
('chili peppers', 'Food & Cooking'),
('ginger', 'Food & Cooking'),
('turmeric', 'Food & Cooking'),
('paprika', 'Food & Cooking'),
('cinnamon', 'Food & Cooking'),
('nutmeg', 'Food & Cooking'),
('cardamom', 'Food & Cooking'),
('black pepper', 'Food & Cooking'),
('salt', 'Food & Cooking'),
('sugar', 'Food & Cooking'),
('vanilla', 'Food & Cooking'),

-- Baking & Desserts
('baking', 'Food & Cooking'),
('desserts', 'Food & Cooking'),
('pastries', 'Food & Cooking'),
('cookies', 'Food & Cooking'),
('cakes', 'Food & Cooking'),
('cupcakes', 'Food & Cooking'),
('brownies', 'Food & Cooking'),
('muffins', 'Food & Cooking'),
('pies', 'Food & Cooking'),
('tarts', 'Food & Cooking'),
('chocolate', 'Food & Cooking'),
('ice cream', 'Food & Cooking'),
('pudding', 'Food & Cooking'),
('macarons', 'Food & Cooking'),
('cheesecake', 'Food & Cooking'),

-- Beverages
('coffee', 'Food & Cooking'),
('tea', 'Food & Cooking'),
('smoothies', 'Food & Cooking'),
('juices', 'Food & Cooking'),
('cocktails', 'Food & Cooking'),
('mocktails', 'Food & Cooking'),
('wine', 'Food & Cooking'),
('beer', 'Food & Cooking'),
('whiskey', 'Food & Cooking'),
('vodka', 'Food & Cooking'),
('rum', 'Food & Cooking'),
('gin', 'Food & Cooking'),
('kombucha', 'Food & Cooking'),
('matcha', 'Food & Cooking'),

-- Specialty Diets
('vegan', 'Food & Cooking'),
('vegetarian', 'Food & Cooking'),
('gluten-free', 'Food & Cooking'),
('keto diet', 'Food & Cooking'),
('paleo diet', 'Food & Cooking'),
('low-carb diet', 'Food & Cooking'),
('dairy-free', 'Food & Cooking'),
('high-protein diet', 'Food & Cooking'),
('raw food diet', 'Food & Cooking'),
('intermittent fasting', 'Food & Cooking'),
('whole30', 'Food & Cooking'),
('mediterranean diet', 'Food & Cooking'),

-- Street Food & Fast Food
('street food', 'Food & Cooking'),
('fast food', 'Food & Cooking'),
('burgers', 'Food & Cooking'),
('pizza', 'Food & Cooking'),
('hot dogs', 'Food & Cooking'),
('fried chicken', 'Food & Cooking'),
('shawarma', 'Food & Cooking'),
('tacos', 'Food & Cooking'),
('kebabs', 'Food & Cooking'),
('noodles', 'Food & Cooking'),
('ramen', 'Food & Cooking'),
('burritos', 'Food & Cooking'),
('gyros', 'Food & Cooking'),
('falafel', 'Food & Cooking'),

-- Food & Nutrition
('nutrition', 'Food & Cooking'),
('healthy eating', 'Food & Cooking'),
('superfoods', 'Food & Cooking'),
('protein', 'Food & Cooking'),
('fiber', 'Food & Cooking'),
('vitamins', 'Food & Cooking'),
('minerals', 'Food & Cooking'),
('hydration', 'Food & Cooking'),
('organic food', 'Food & Cooking'),
('fermented foods', 'Food & Cooking'),
('plant-based diet', 'Food & Cooking'),
('probiotics', 'Food & Cooking'),

-- Cooking Appliances & Tools
('kitchen gadgets', 'Food & Cooking'),
('blender', 'Food & Cooking'),
('mixer', 'Food & Cooking'),
('food processor', 'Food & Cooking'),
('air fryer', 'Food & Cooking'),
('instant pot', 'Food & Cooking'),
('slow cooker', 'Food & Cooking'),
('pressure cooker', 'Food & Cooking'),
('cast iron skillet', 'Food & Cooking'),
('nonstick pan', 'Food & Cooking'),
('chef knife', 'Food & Cooking'),
('cutting board', 'Food & Cooking'),
('baking sheets', 'Food & Cooking'),
('measuring cups', 'Food & Cooking'),

-- Food Industry & Trends
('food blogging', 'Food & Cooking'),
('restaurant reviews', 'Food & Cooking'),
('food photography', 'Food & Cooking'),
('cooking shows', 'Food & Cooking'),
('Michelin star restaurants', 'Food & Cooking'),
('food festivals', 'Food & Cooking'),
('farm-to-table', 'Food & Cooking'),
('sustainable food', 'Food & Cooking'),
('food waste reduction', 'Food & Cooking'),
('gourmet dining', 'Food & Cooking');

INSERT INTO keywords (word, category)
VALUES
-- General Politics & Society
('politics', 'Politics & Society'),
('government', 'Politics & Society'),
('public policy', 'Politics & Society'),
('law', 'Politics & Society'),
('legislation', 'Politics & Society'),
('governance', 'Politics & Society'),
('democracy', 'Politics & Society'),
('voting', 'Politics & Society'),
('elections', 'Politics & Society'),
('political parties', 'Politics & Society'),
('political debate', 'Politics & Society'),
('campaigns', 'Politics & Society'),
('political ideology', 'Politics & Society'),
('left-wing politics', 'Politics & Society'),
('right-wing politics', 'Politics & Society'),
('centrist politics', 'Politics & Society'),
('liberalism', 'Politics & Society'),
('conservatism', 'Politics & Society'),
('socialism', 'Politics & Society'),
('communism', 'Politics & Society'),
('fascism', 'Politics & Society'),
('anarchism', 'Politics & Society'),

-- Government & Institutions
('executive branch', 'Politics & Society'),
('legislative branch', 'Politics & Society'),
('judicial branch', 'Politics & Society'),
('parliament', 'Politics & Society'),
('congress', 'Politics & Society'),
('senate', 'Politics & Society'),
('presidency', 'Politics & Society'),
('prime minister', 'Politics & Society'),
('monarchy', 'Politics & Society'),
('bureaucracy', 'Politics & Society'),
('diplomacy', 'Politics & Society'),
('foreign policy', 'Politics & Society'),

-- Law & Justice
('constitutional law', 'Politics & Society'),
('criminal law', 'Politics & Society'),
('civil rights', 'Politics & Society'),
('human rights', 'Politics & Society'),
('legal system', 'Politics & Society'),
('supreme court', 'Politics & Society'),
('lawsuits', 'Politics & Society'),
('justice reform', 'Politics & Society'),
('policing', 'Politics & Society'),
('law enforcement', 'Politics & Society'),
('international law', 'Politics & Society'),
('immigration law', 'Politics & Society'),

-- Social Issues & Activism
('civil rights movement', 'Politics & Society'),
('social justice', 'Politics & Society'),
('gender equality', 'Politics & Society'),
('racial equality', 'Politics & Society'),
('LGBTQ+ rights', 'Politics & Society'),
('disability rights', 'Politics & Society'),
(N'women’s rights', 'Politics & Society'),
('humanitarian aid', 'Politics & Society'),
('poverty', 'Politics & Society'),
('homelessness', 'Politics & Society'),
('income inequality', 'Politics & Society'),
(N'workers’ rights', 'Politics & Society'),
('unions', 'Politics & Society'),
('environmental justice', 'Politics & Society'),
('climate policy', 'Politics & Society'),

-- International Relations & Global Politics
('United Nations', 'Politics & Society'),
('NATO', 'Politics & Society'),
('geopolitics', 'Politics & Society'),
('globalization', 'Politics & Society'),
('diplomatic relations', 'Politics & Society'),
('foreign aid', 'Politics & Society'),
('trade agreements', 'Politics & Society'),
('economic sanctions', 'Politics & Society'),
('global conflicts', 'Politics & Society'),
('wars', 'Politics & Society'),
('peace treaties', 'Politics & Society'),
('military alliances', 'Politics & Society'),
('intelligence agencies', 'Politics & Society'),

-- Media & Political Influence
('political journalism', 'Politics & Society'),
('news media', 'Politics & Society'),
('propaganda', 'Politics & Society'),
('fake news', 'Politics & Society'),
('censorship', 'Politics & Society'),
('freedom of speech', 'Politics & Society'),
('press freedom', 'Politics & Society'),
('political advertising', 'Politics & Society'),
('social media influence', 'Politics & Society'),
('lobbying', 'Politics & Society'),
('political funding', 'Politics & Society'),
('campaign finance', 'Politics & Society'),

-- Economic & Social Policies
('taxation', 'Politics & Society'),
('welfare state', 'Politics & Society'),
('healthcare policy', 'Politics & Society'),
('education policy', 'Politics & Society'),
('housing policy', 'Politics & Society'),
('minimum wage', 'Politics & Society'),
('universal basic income', 'Politics & Society'),
('economic growth', 'Politics & Society'),
('free market', 'Politics & Society'),
('social security', 'Politics & Society'),
('pension systems', 'Politics & Society'),
('labor laws', 'Politics & Society'),
('public safety', 'Politics & Society'),

-- Crime & Punishment
('criminal justice', 'Politics & Society'),
('prisons', 'Politics & Society'),
('death penalty', 'Politics & Society'),
('police reform', 'Politics & Society'),
('gun control', 'Politics & Society'),
('drug policy', 'Politics & Society'),
('organized crime', 'Politics & Society'),
('human trafficking', 'Politics & Society'),
('cybercrime', 'Politics & Society'),

-- Ethics & Morality in Politics
('political corruption', 'Politics & Society'),
('ethics in government', 'Politics & Society'),
('whistleblowing', 'Politics & Society'),
('scandals', 'Politics & Society'),
('accountability', 'Politics & Society'),
('transparency', 'Politics & Society'),
('public trust', 'Politics & Society'),
('moral philosophy', 'Politics & Society'),
('political philosophy', 'Politics & Society');

INSERT INTO keywords (word, category)
VALUES
-- General History
('history', 'History & Philosophy'),
('ancient history', 'History & Philosophy'),
('medieval history', 'History & Philosophy'),
('modern history', 'History & Philosophy'),
('contemporary history', 'History & Philosophy'),
('historical events', 'History & Philosophy'),
('world history', 'History & Philosophy'),
('timeline', 'History & Philosophy'),
('archaeology', 'History & Philosophy'),
('historical records', 'History & Philosophy'),
('historical figures', 'History & Philosophy'),
('primary sources', 'History & Philosophy'),
('historical analysis', 'History & Philosophy'),

-- Civilizations & Empires
('ancient Egypt', 'History & Philosophy'),
('ancient Greece', 'History & Philosophy'),
('Roman Empire', 'History & Philosophy'),
('Byzantine Empire', 'History & Philosophy'),
('Ottoman Empire', 'History & Philosophy'),
('Mongol Empire', 'History & Philosophy'),
('British Empire', 'History & Philosophy'),
('Chinese dynasties', 'History & Philosophy'),
('Mesoamerican civilizations', 'History & Philosophy'),
('Mayan civilization', 'History & Philosophy'),
('Incan civilization', 'History & Philosophy'),
('Aztec civilization', 'History & Philosophy'),
('Persian Empire', 'History & Philosophy'),

-- Wars & Revolutions
('ancient wars', 'History & Philosophy'),
('Peloponnesian War', 'History & Philosophy'),
('Punic Wars', 'History & Philosophy'),
(N'Hundred Years’ War', 'History & Philosophy'),
('Napoleonic Wars', 'History & Philosophy'),
('American Revolution', 'History & Philosophy'),
('French Revolution', 'History & Philosophy'),
('World War I', 'History & Philosophy'),
('World War II', 'History & Philosophy'),
('Cold War', 'History & Philosophy'),
('Vietnam War', 'History & Philosophy'),
('Korean War', 'History & Philosophy'),
('Civil War', 'History & Philosophy'),
('Independence movements', 'History & Philosophy'),

-- Historical Leaders & Thinkers
('Julius Caesar', 'History & Philosophy'),
('Cleopatra', 'History & Philosophy'),
('Alexander the Great', 'History & Philosophy'),
('Napoleon Bonaparte', 'History & Philosophy'),
('Abraham Lincoln', 'History & Philosophy'),
('Winston Churchill', 'History & Philosophy'),
('Mahatma Gandhi', 'History & Philosophy'),
('Karl Marx', 'History & Philosophy'),
('Plato', 'History & Philosophy'),
('Socrates', 'History & Philosophy'),
('Aristotle', 'History & Philosophy'),
('Confucius', 'History & Philosophy'),
('Sun Tzu', 'History & Philosophy'),
('Renaissance thinkers', 'History & Philosophy'),
('Enlightenment philosophers', 'History & Philosophy'),

-- Historical Periods & Movements
('Renaissance', 'History & Philosophy'),
('Enlightenment', 'History & Philosophy'),
('Industrial Revolution', 'History & Philosophy'),
('Scientific Revolution', 'History & Philosophy'),
('Age of Exploration', 'History & Philosophy'),
('Colonialism', 'History & Philosophy'),
('Imperialism', 'History & Philosophy'),
('Great Depression', 'History & Philosophy'),
('Cold War era', 'History & Philosophy'),

-- Philosophy & Thought
('philosophy', 'History & Philosophy'),
('metaphysics', 'History & Philosophy'),
('epistemology', 'History & Philosophy'),
('ethics', 'History & Philosophy'),
('logic', 'History & Philosophy'),
('political philosophy', 'History & Philosophy'),
('moral philosophy', 'History & Philosophy'),
('aesthetics', 'History & Philosophy'),
('existentialism', 'History & Philosophy'),
('utilitarianism', 'History & Philosophy'),
('stoicism', 'History & Philosophy'),
('nihilism', 'History & Philosophy'),
('pragmatism', 'History & Philosophy'),
('idealism', 'History & Philosophy'),
('realism', 'History & Philosophy'),
('postmodernism', 'History & Philosophy'),
('structuralism', 'History & Philosophy'),

-- Religious & Spiritual Thought
('theology', 'History & Philosophy'),
('comparative religion', 'History & Philosophy'),
('Christianity', 'History & Philosophy'),
('Islam', 'History & Philosophy'),
('Buddhism', 'History & Philosophy'),
('Hinduism', 'History & Philosophy'),
('Judaism', 'History & Philosophy'),
('Taoism', 'History & Philosophy'),
('Shintoism', 'History & Philosophy'),
('agnosticism', 'History & Philosophy'),
('atheism', 'History & Philosophy'),
('religious philosophy', 'History & Philosophy'),
('spirituality', 'History & Philosophy'),

-- Political & Social Philosophy
('social contract theory', 'History & Philosophy'),
('democratic theory', 'History & Philosophy'),
('Marxism', 'History & Philosophy'),
('capitalism', 'History & Philosophy'),
('socialism', 'History & Philosophy'),
('communism', 'History & Philosophy'),
('anarchism', 'History & Philosophy'),
('liberalism', 'History & Philosophy'),
('conservatism', 'History & Philosophy'),
('feminist philosophy', 'History & Philosophy'),
('critical theory', 'History & Philosophy'),

-- Science & Philosophy
('scientific method', 'History & Philosophy'),
('philosophy of science', 'History & Philosophy'),
('rationalism', 'History & Philosophy'),
('empiricism', 'History & Philosophy'),
('positivism', 'History & Philosophy'),
('determinism', 'History & Philosophy'),
('quantum philosophy', 'History & Philosophy'),

-- Ethics & Morality
('applied ethics', 'History & Philosophy'),
('bioethics', 'History & Philosophy'),
('business ethics', 'History & Philosophy'),
('environmental ethics', 'History & Philosophy'),
('moral dilemmas', 'History & Philosophy'),
('free will', 'History & Philosophy'),
('moral relativism', 'History & Philosophy'),
('virtue ethics', 'History & Philosophy'),
('deontology', 'History & Philosophy'),
('consequentialism', 'History & Philosophy'),

-- Historical Discoveries & Theories
('heliocentric theory', 'History & Philosophy'),
('Darwinian evolution', 'History & Philosophy'),
('Newtonian physics', 'History & Philosophy'),
('relativity theory', 'History & Philosophy'),
('quantum mechanics', 'History & Philosophy'),
('atomic theory', 'History & Philosophy'),
('Big Bang theory', 'History & Philosophy'),
('anthropic principle', 'History & Philosophy'),

-- Philosophy in Literature & Culture
('philosophical novels', 'History & Philosophy'),
('literary theory', 'History & Philosophy'),
('cultural history', 'History & Philosophy'),
('mythology', 'History & Philosophy'),
('folklore', 'History & Philosophy'),
('oral traditions', 'History & Philosophy'),
('historical fiction', 'History & Philosophy');

INSERT INTO keywords (word, category)
VALUES
-- General Vietnam Topics
('Vietnam', 'Vietnam'),
('Vietnamese culture', 'Vietnam'),
('Vietnamese language', 'Vietnam'),
('Vietnamese history', 'Vietnam'),
('Vietnamese traditions', 'Vietnam'),
('Vietnamese cuisine', 'Vietnam'),
('Vietnamese music', 'Vietnam'),
('Vietnamese literature', 'Vietnam'),
('Vietnamese economy', 'Vietnam'),
('Vietnamese politics', 'Vietnam'),
('Vietnamese geography', 'Vietnam'),
('Vietnamese people', 'Vietnam'),

-- Geography & Places
('Hanoi', 'Vietnam'),
('Ho Chi Minh City', 'Vietnam'),
('Saigon', 'Vietnam'),
('Da Nang', 'Vietnam'),
('Hue', 'Vietnam'),
('Hoi An', 'Vietnam'),
('Nha Trang', 'Vietnam'),
('Ha Long Bay', 'Vietnam'),
('Phong Nha-Ke Bang', 'Vietnam'),
('Mekong Delta', 'Vietnam'),
('Sapa', 'Vietnam'),
('Ba Na Hills', 'Vietnam'),
('Con Dao Islands', 'Vietnam'),
('Phu Quoc', 'Vietnam'),
('Cat Ba Island', 'Vietnam'),
('Cao Bang', 'Vietnam'),
('Dalat', 'Vietnam'),
('Tam Coc', 'Vietnam'),

-- History
('Vietnam War', 'Vietnam'),
('French Indochina', 'Vietnam'),
('Nguyen Dynasty', 'Vietnam'),
('Trung Sisters', 'Vietnam'),
('Ho Chi Minh', 'Vietnam'),
('Battle of Dien Bien Phu', 'Vietnam'),
('Tet Offensive', 'Vietnam'),
('Reunification of Vietnam', 'Vietnam'),
('Colonial Vietnam', 'Vietnam'),
('Chinese domination of Vietnam', 'Vietnam'),
('Vietnamese resistance', 'Vietnam'),
('Paris Peace Accords', 'Vietnam'),

-- Culture & Festivals
('Tet Festival', 'Vietnam'),
('Mid-Autumn Festival', 'Vietnam'),
('Hue Festival', 'Vietnam'),
('Perfume Pagoda Festival', 'Vietnam'),
('Lim Festival', 'Vietnam'),
('Hoi An Lantern Festival', 'Vietnam'),
('Vietnamese wedding traditions', 'Vietnam'),
('Ao dai', 'Vietnam'),
('Vietnamese folk music', 'Vietnam'),
('Cheo', 'Vietnam'),
('Cai luong', 'Vietnam'),
('Vietnamese water puppetry', 'Vietnam'),

-- Vietnamese Cuisine
('pho', 'Vietnam'),
('banh mi', 'Vietnam'),
('bun cha', 'Vietnam'),
('com tam', 'Vietnam'),
('goi cuon', 'Vietnam'),
('che dessert', 'Vietnam'),
('ca phe sua da', 'Vietnam'),
('Vietnamese coffee', 'Vietnam'),
('nuoc mam', 'Vietnam'),
('banh xeo', 'Vietnam'),
('hu tieu', 'Vietnam'),
('cha ca', 'Vietnam'),
('bun bo Hue', 'Vietnam'),

-- Economy & Business
('Vietnamese stock market', 'Vietnam'),
('Vietnamese exports', 'Vietnam'),
('Vietnamese agriculture', 'Vietnam'),
('Vietnamese manufacturing', 'Vietnam'),
('Vietnamese startup ecosystem', 'Vietnam'),
('foreign direct investment in Vietnam', 'Vietnam'),
('Vietnamese tourism industry', 'Vietnam'),
('Vietnamese real estate market', 'Vietnam'),

-- Politics & Government
('Vietnamese Communist Party', 'Vietnam'),
('Ho Chi Minh ideology', 'Vietnam'),
('Socialist Republic of Vietnam', 'Vietnam'),
('Vietnamese Constitution', 'Vietnam'),
('Vietnamese national assembly', 'Vietnam'),
('Doi Moi reforms', 'Vietnam'),
('Vietnamese foreign policy', 'Vietnam'),
('Vietnam-China relations', 'Vietnam'),
('Vietnam-US relations', 'Vietnam'),

-- Natural Wonders & Wildlife
('Son Doong Cave', 'Vietnam'),
('Ba Be National Park', 'Vietnam'),
('Pu Luong Nature Reserve', 'Vietnam'),
('Phu Quoc National Park', 'Vietnam'),
('Con Dao National Park', 'Vietnam'),
('Vietnamese wildlife', 'Vietnam'),
('Vietnamese biodiversity', 'Vietnam'),

-- Transport & Infrastructure
('Vietnamese railway system', 'Vietnam'),
('Vietnamese highways', 'Vietnam'),
('Tan Son Nhat Airport', 'Vietnam'),
('Noi Bai Airport', 'Vietnam'),
('Vietnamese public transportation', 'Vietnam'),
('Vietnamese motorbikes', 'Vietnam'),
('Vietnamese traffic laws', 'Vietnam'),
('Vietnamese roads', 'Vietnam'),

-- Education & Science
('Vietnamese universities', 'Vietnam'),
('Vietnam National University', 'Vietnam'),
('Vietnamese students', 'Vietnam'),
('Vietnamese education system', 'Vietnam'),
('STEM in Vietnam', 'Vietnam'),
('Vietnamese scientific research', 'Vietnam'),

-- Sports & Recreation
('Vietnamese football', 'Vietnam'),
('Vietnam national football team', 'Vietnam'),
('V.League 1', 'Vietnam'),
('Vietnamese martial arts', 'Vietnam'),
('Vovinam', 'Vietnam'),
('Vietnamese esports', 'Vietnam'),
('Vietnamese cycling', 'Vietnam'),

-- Tourism & Travel
('Vietnamese backpacking', 'Vietnam'),
('motorbike tours in Vietnam', 'Vietnam'),
('Vietnamese homestays', 'Vietnam'),
('Vietnamese street food tours', 'Vietnam'),
('beaches in Vietnam', 'Vietnam'),
('Vietnamese visas', 'Vietnam'),
('Vietnamese travel agencies', 'Vietnam'),
('Vietnamese hotels', 'Vietnam'),
('Vietnamese hostels', 'Vietnam'),
('Vietnamese budget travel', 'Vietnam'),

-- Traditional Medicine & Health
('Vietnamese traditional medicine', 'Vietnam'),
('Vietnamese herbal remedies', 'Vietnam'),
('Vietnamese acupuncture', 'Vietnam'),
('Vietnamese hospitals', 'Vietnam'),
('Vietnamese healthcare system', 'Vietnam');

INSERT INTO keywords (word, category)
VALUES
-- General TUYU-related keywords
(N'ツユ', 'JPOP'),
('TUYU', 'JPOP'),
(N'ロックな君とはお別れだ', 'JPOP'),
('Goodbye to Rock You', 'JPOP'),
(N'藍月なくる', 'JPOP'), -- Aizuki Nakuru (Vocalist)
(N'ぷす', 'JPOP'),       -- Pusu (Guitarist, Composer)
('miro', 'JPOP'),        -- Miro (Pianist)
('JPOP', 'Music'),
('Japanese rock', 'Music'),
(N'ロック', 'Music'),
(N'別れ', 'Emotions'),
(N'才能', 'Emotions'),
(N'劣等生', 'Emotions'), -- "Inferior student" (from the lyrics)
(N'嫉妬', 'Emotions'),   -- "Jealousy"
(N'優等生', 'Emotions'), -- "Honor student"

-- Lyrics (Japanese)
(N'ロックな君とはお別れだ', 'Lyrics'),
(N'僕に目もくれないで', 'Lyrics'),
(N'才能に嫉妬して', 'Lyrics'),
(N'馬鹿にすんなよ', 'Lyrics'),
(N'傍迷惑だ', 'Lyrics'),
(N'僕は君に囚われたまま', 'Lyrics'),
(N'憧れて', 'Lyrics'),
(N'芯が折れていた', 'Lyrics'),
(N'全部 中途半端になって', 'Lyrics'),
(N'卑怯者と笑われ', 'Lyrics'),
(N'雑草の如く転んでも踏まれても立ち上がる', 'Lyrics'),
(N'ロックに生きたいね', 'Lyrics'),
(N'じゃあね', 'Lyrics'),

-- Lyrics (English Translation)
('Goodbye to rock you', 'Lyrics'),
(N'Don’t look at me and keep going ahead', 'Lyrics'),
('I was jealous of your talent', 'Lyrics'),
(N'Don’t make fun of me', 'Lyrics'),
(N'You’ve always captivated me', 'Lyrics'),
('I always admired you', 'Lyrics'),
('But I was broken inside', 'Lyrics'),
('Everything became half-baked', 'Lyrics'),
('They called me a coward', 'Lyrics'),
('Like a weed, even if I fall or get trampled, I will rise again', 'Lyrics'),
('I want to live rock', 'Lyrics'),
('So goodbye', 'Lyrics');